import type { Metadata } from "next";
import React from "react";
import "@/common/styles/global.scss";
import TopLoader from "@/layout-components/top-loader";

export const metadata: Metadata = {
  // Change the title app
  title: "Create Next App",
  // Change the description app
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        This is the layout of app <br />
        ------------------------------------ <br />
        {children}
        <TopLoader />
      </body>
    </html>
  );
}
